# FINDING SVD m < n

In [ ]:
import numpy as np
np.set_printoptions(precision = 2, suppress = True)

a = np.array([[1,2,3,4],[1,1,2,3,],[0,1,1,0]])
print(a)


[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


In [3]:
u , s, vh = np.linalg.svd(a, full_matrices = True )
u.shape, s.shape, vh.shape

((3, 3), (3,), (4, 4))

In [5]:
u
u.dot(u.T)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [8]:
vh
vh.dot(vh.T)

array([[ 1., -0., -0.,  0.],
       [-0.,  1.,  0.,  0.],
       [-0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [ ]:
s


array([6.75, 1.17, 0.22])

In [11]:
#Reconstruct the s
sd = np.diag(s)
sd

array([[6.75, 0.  , 0.  ],
       [0.  , 1.17, 0.  ],
       [0.  , 0.  , 0.22]])

In [14]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
b[:, :-1] = sd
b
sigma = b 
sigma

array([[6.75, 0.  , 0.  , 0.  ],
       [0.  , 1.17, 0.  , 0.  ],
       [0.  , 0.  , 0.22, 0.  ]])

In [20]:
print(np.dot(np.dot(u, sigma),vh))

[[1. 2. 3. 4.]
 [1. 1. 2. 3.]
 [0. 1. 1. 0.]]


# LOW RANK APPROX 


In [ ]:
s =np.array([6.75, 1.17, 0])
s

array([6.75, 1.17, 0.  ])

In [22]:
sd = np.diag(s)
sd

array([[6.75, 0.  , 0.  ],
       [0.  , 1.17, 0.  ],
       [0.  , 0.  , 0.  ]])

In [23]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
b[:, :-1] = sd
b
sigma = b 
sigma

array([[6.75, 0.  , 0.  , 0.  ],
       [0.  , 1.17, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [26]:
print(np.dot(np.dot(u, sigma),vh))
print(a)

[[ 1.1   1.96  3.05  3.95]
 [ 0.88  1.06  1.93  3.06]
 [-0.06  1.02  0.97  0.03]]
[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]]


# m > n

In [27]:
A = np.array([[1,2,3,4,],[1,1,2,3],[0,1,1,0],[0,2,2,0],[0,5,5,0]])
A

array([[1, 2, 3, 4],
       [1, 1, 2, 3],
       [0, 1, 1, 0],
       [0, 2, 2, 0],
       [0, 5, 5, 0]])

In [ ]:
u , s, vh = np.linalg.svd(A )
u.shape, s.shape, vh.shape

((5, 5), (4,), (4, 4))

In [32]:
u

array([[-0.52, -0.6 ,  0.61,  0.  , -0.  ],
       [-0.34, -0.51, -0.79, -0.  ,  0.  ],
       [-0.14,  0.11, -0.01,  0.92,  0.35],
       [-0.29,  0.23, -0.02,  0.27, -0.89],
       [-0.72,  0.56, -0.06, -0.29,  0.29]])

In [34]:
s

array([9.23, 4.45, 0.23, 0.  ])

In [36]:
vh

array([[-0.09, -0.61, -0.71, -0.33],
       [-0.25,  0.37,  0.13, -0.88],
       [-0.77,  0.38, -0.39,  0.33],
       [ 0.58,  0.58, -0.58,  0.  ]])

In [33]:
sd = np.diag(s)
sd

array([[9.23, 0.  , 0.  , 0.  ],
       [0.  , 4.45, 0.  , 0.  ],
       [0.  , 0.  , 0.23, 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [ ]:
new_row = np.array([[0., 0., 0., 0.]])
sigma1 = np.vstack((sd, new_row))
sigma1

array([[9.23, 0.  , 0.  , 0.  ],
       [0.  , 4.45, 0.  , 0.  ],
       [0.  , 0.  , 0.23, 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [45]:
u.shape, sigma.shape, vh.shape

((5, 5), (5, 4), (4, 4))

In [50]:
print(np.dot(np.dot(u,sigma),vh))
print(A)

[[1. 2. 3. 4.]
 [1. 1. 2. 3.]
 [0. 1. 1. 0.]
 [0. 2. 2. 0.]
 [0. 5. 5. 0.]]
[[1 2 3 4]
 [1 1 2 3]
 [0 1 1 0]
 [0 2 2 0]
 [0 5 5 0]]
