In [16]:
import numpy as np
v = np.array([1, -1, 2])
w = np.array([2,5,2])


print(v+w)

[3 4 4]


In [17]:
print(v-w)

[-1 -6  0]


#### Scalar multiplication

In [18]:
print(2*v)

[ 2 -2  4]


#### Length of vector

In [19]:
print(np.linalg.norm(w))

5.744562646538029


#### Dot product

In [15]:
print(np.dot(v,w))

1
